const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const context=vm.createContext({});vm.runInContext(fs.readFileSync('classes/Expedition.js','utf8')+';globalThis.Expedition=Expedition',context);
function fixture(){const e=Object.create(context.Expedition.prototype);e.stage='nests';e.index=0;e.wave=3;e.token={};e.nodes=[{x:0,y:0},{x:500,y:0}];e.game={state:'playing',player:{x:0,y:0,hp:50,maxHp:100,shield:0,bulletDamage:10},survivalTime:10,_announce(){},triggerUpgrade(){this.rewards=(this.rewards||0)+1;this.state='upgrading';}};return e;}
test('nest reward waits for every guard and is awarded only once',()=>{const e=fixture(),guard={active:true,hp:10,chapterGuard:e.token};e.guards=[guard];e.update();assert.equal(e.index,0);guard.hp=0;e.update();assert.equal(e.index,1);assert.equal(e.game.rewards,1);e.update();assert.equal(e.game.rewards,1);});
test('pooled guards cannot keep an old encounter alive',()=>{const e=fixture();e.guards=[{active:true,hp:100,chapterGuard:{}}];assert.equal(e.remaining,0);});
test('supply reward cannot be claimed twice',()=>{const e=fixture();e.stage='choose';e.choose('supply');e.choose('supply');assert.equal(e.game.player.hp,90);assert.equal(e.game.player.shield,15);assert.equal(e.stage,'gate');});
test('victory requires final boss stage and a living player',()=>{const e=fixture();assert.equal(e.win(),false);e.stage='boss';e.game.player.hp=0;assert.equal(e.win(),false);e.game.player.hp=1;e.modal=()=>{};assert.equal(e.win(),true);assert.equal(e.game.state,'victory');assert.equal(e.win(),false);});

test('first wave gives a two second warning and freezes while paused',()=>{const e=fixture();e.wave=0;e.guards=[];let spawned=0;e.spawnGuards=()=>{spawned++;return true;};e.update();assert.equal(spawned,0);assert.equal(e.countdown,2);assert.equal(e.fighting,true);e.game.state='paused';e.update();assert.equal(spawned,0);e.game.state='playing';e.game.survivalTime=12;e.update();assert.equal(spawned,1);assert.equal(e.wave,1);assert.equal(e.nextWaveAt,0);});
test('clearing a nest resets its countdown before travelling to the next',()=>{const e=fixture();e.nextWaveAt=9;e.guards=[{active:false,hp:0,chapterGuard:e.token}];e.update();assert.equal(e.nextWaveAt,0);assert.equal(e.nodes[0].clearedAt,10);assert.equal(e.index,1);});
